spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 3574135741
  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-a69d6cc96e7848b6b5edeebbe688316d
      chat:
        options:
          model: qwen-plus
server:
  port: 8002

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    org.progingo.aistudy: debug
